export const TASK_DAILY_MINUTES_LIMIT = 360;
export const HABIT_DEFAULT_DURATION_MINUTES = 30;
export const HABIT_DEFAULT_START_MINUTES = 7 * 60;
export const STUDY_BLOCK_DAY_START_MINUTES = 9 * 60;
export const STUDY_BLOCK_DAY_END_MINUTES = 21 * 60;
export const STUDY_BLOCK_GAP_MINUTES = 10;
